# Generated by Django 4.2.28 on 2026-03-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubCotegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(max_length=500)),
                ('describ_service', models.CharField(max_length=5000)),
                ('price', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media/')),
                ('serv_cotegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.servicecotegory')),
            ],
        ),
    ]
