# Generated by Django 4.2.28 on 2026-03-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_servicesubcotegory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Name', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('u_img', models.ImageField(default='', upload_to='media/')),
            ],
        ),
        migrations.RenameField(
            model_name='servicesubcotegory',
            old_name='type_service',
            new_name='type_of_serv_cotegory',
        ),
        migrations.RemoveField(
            model_name='servicecotegory',
            name='image',
        ),
        migrations.AlterField(
            model_name='servicecotegory',
            name='describ_service',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='servicecotegory',
            name='serv_cotegory',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('headings', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='media/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.servicecotegory')),
            ],
        ),
    ]
