# Generated by Django 4.2.28 on 2026-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usercomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubcotegory',
            name='about_the_service',
            field=models.CharField(default='', max_length=500),
        ),
    ]
