# Generated by Django 4.2.28 on 2026-03-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_servicesubcotegory_about_the_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='desc',
        ),
        migrations.AddField(
            model_name='blogs',
            name='desc1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogs',
            name='desc2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogs',
            name='desc3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogs',
            name='desc4',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogs',
            name='siub_head1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogs',
            name='sub_head2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='headings',
            field=models.CharField(default='', max_length=200),
        ),
    ]
