# Generated by Django 4.2.28 on 2026-03-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_blogs_desc_blogs_desc1_blogs_desc2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('service_cotegory', models.CharField(max_length=100)),
                ('selected_service_type', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
